# Generated by Django 4.2.7 on 2023-12-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_description_lesson_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_1', models.CharField(max_length=255)),
                ('task_2', models.CharField(max_length=255)),
                ('task_3', models.CharField(max_length=255)),
                ('task_4', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('grade_1', models.IntegerField(blank=True, null=True)),
                ('grade_2', models.IntegerField(blank=True, null=True)),
                ('grade_3', models.IntegerField(blank=True, null=True)),
                ('grade_4', models.IntegerField(blank=True, null=True)),
                ('total_grade', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
    ]
