# Generated by Django 4.2.7 on 2023-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_studenthomework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='grade_1',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='grade_2',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='grade_3',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='grade_4',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='total_grade',
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='watch_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
